In [3]:
import sys

project_path = r'D:\programming\specializaion track\Data Engineering\Big Data\Python\ecommerce-data-pipeline'
sys.path.insert(0, project_path)
import src.ingestion

In [26]:
import importlib
import src.cleaning
import numpy as np
import pandas as pd

importlib.reload(src.cleaning)

In [ ]:
from src.ingestion import load_data
from src.cleaning import clean_data
from src.Transformation import prepare_sales_data
from src.analysis import *

df = load_data('../Data/raw/online_retail_II.csv')

df = clean_data(df)

df = prepare_sales_data(df)

customer_summary = create_customer_summary(df)
product_summary = create_product_summary(df)
country_summary = create_Country_summary(df)
monthly_summary = create_monthly_summary(df)

In [20]:
customer_summary

      Customer ID  Revenue  Quantity
0           12346   -51.74        53
1           12347  3578.67      1567
2           12348    478.2       114
3           12349  3947.94      1057
4           12350    314.0       173
...           ...      ...       ...
5782        18283   2664.9      1679
5783        18284    270.9       142
5784        18285    223.0        65
5785        18286  1119.79       472
5786        18287  1801.29       964

[5787 rows x 3 columns]

In [21]:
product_summary

         StockCode  Revenue  Quantity
0            10002  1743.79      1924
1           10002R    20.57         4
2            10080    62.99       145
3            10109     1.68         4
4            10120    54.54       244
...            ...      ...       ...
4871  gift_0001_40   166.09         5
4872  gift_0001_50   253.59         6
4873  gift_0001_70    59.57         1
4874  gift_0001_80      0.0         0
4875             m    15.05         5

[4876 rows x 3 columns]